[env]
DEBUG_OPTION = "-g -ggdb -fstack-usage -fno-omit-frame-pointer -fsanitize=address"

[tasks.run]
description = "Run the single file application"
command = "script"
args = ["-c", "./a.out", "output.txt"]

[tasks.copy-output]
description = "Copy the output to the clipboard"
script = '''
#!/bin/bash

tail -n +2 output.txt | head -n -2 | win32yank.exe -i
rm -f output.txt
'''

[tasks.build]
description = "Build the single source file application"
command = "mold"
args = [
  "-run",
  "cc",
  "-g",
  "-ggdb",
  "-fstack-usage",
  "-fno-omit-frame-pointer",
  "-fsanitize=address",
  "-o",
  "a.out",
  "${@}",
]

[tasks.build-and-run]
description = "Build and run the single file application"
run_task = { name = ["build", "run", "copy-output"] }
